### ISSUE TITLE
Vignette re-building failed

### ISSUE THREAD

**Issue by jafernandez01** [AAGI-Org-AU-Public/theme.aagi#4]
I got an error when trying to install the package. It appears to be related to the build of the Cookbook.Rmd vignette. Below the error details.

**Command used**
`remotes::install_github("AAGI-Org-AU-Public/theme.aagi",
                        build_vignettes = TRUE,
                        dependencies = TRUE
)
`

**Error message**
> E  creating vignettes (3s)
   --- re-building ‘Cookbook.Rmd’ using rmarkdown
   Warning in doTryCatch(return(expr), name, parentenv, handler) :
     "panel.first" is not a graphical parameter
   Warning in doTryCatch(return(expr), name, parentenv, handler) :
     "panel.first" is not a graphical parameter
   Warning in doTryCatch(return(expr), name, parentenv, handler) :
     "panel.first" is not a graphical parameter
   Warning in doTryCatch(return(expr), name, parentenv, handler) :
     "panel.first" is not a graphical parameter
   
>    Quitting from lines 238-271 [aagi-facet-example] (Cookbook.Rmd)
   Error: processing vignette 'Cookbook.Rmd' failed with diagnostics:
   recursive indexing failed at level 2
   
>    --- failed re-building ‘Cookbook.Rmd’
   
>    SUMMARY: processing the following file failed:
     ‘Cookbook.Rmd’
   
>    Error: Vignette re-building failed.
   Execution halted
Error: Failed to install 'theme.aagi' from GitHub:
  ! System command 'R' failed

**Comment by adamhsparks** [comment]
Yes, I'm aware. There isn't a release version of this package yet. If you'd like to fix the error in the Vignette, I'd take a PR.

**Comment by adamhsparks** [comment]
Though the package does install otherwise, I'm using it, just without the vignette.
